spring.data.mongodb.uri=mongodb+srv://andresvivasb_db_user:RUNtiLLxuSM85xwt@cluster0.iyadhmw.mongodb.net/?appName=Cluster0
spring.data.mongodb.database=dosw_library
server.port=8080
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
spring.autoconfigure.exclude=\
  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.jpa.JpaRepositoriesAutoConfiguration