spring.application.name=DOSW-Library
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
server.port=8443
server.ssl.enabled=true
server.ssl.key-store=classpath:dosw-keystore.p12
server.ssl.key-store-password=changeit
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=dosw